openapi: 3.0.0
info:
  title: WASAText API
  description: API for the WASAText instant messaging application.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      scheme: bearer

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: Unique user ID
        username:
          type: string
          description: User's display name
        photo:
          type: string
          description: Base64 encoded photo or URL (optional)
      required:
        - id
        - username

    Conversation:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          description: Name of the conversation (if group)
        type:
          type: string
          enum: [direct, group]
        members:
          type: array
          items:
            $ref: '#/components/schemas/User'
        last_message:
           $ref: '#/components/schemas/Message'
      required:
        - id
        - type
        - members

    Message:
      type: object
      properties:
        id:
          type: integer
        conversation_id:
          type: integer
        sender_id:
          type: integer
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        reply_to_message_id:
           type: integer
        forward_from_message_id:
           type: integer
        photo:
           type: string
        status:
           type: string
           enum: [sent, received, read]
        reactions:
           type: array
           items:
             type: object
             properties:
               user_id:
                 type: integer
               emoji:
                 type: string
       required:
        - id
        - conversation_id
        - sender_id
        - content
        - timestamp

    Group:
      type: object
      properties:
        conversation_id:
           type: integer
        name:
           type: string
        photo:
           type: string


paths:
  /session:
    post:
      operationId: doLogin
      summary: Login user
      description: Returns a session token (and user info). If user needs to be created, it happens here.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
                - username
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID to identify this user in future requests
                  identifier:
                    type: string
        '400':
          description: Invalid input

  /users:
    get:
      operationId: searchUsers
      summary: Search for users
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of users found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    security:
      - bearerAuth: []

  /users/me/name:
    put:
      operationId: setMyUserName
      security:
        - bearerAuth: []
      summary: Set the username for the authenticated user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses:
        '200':
          description: Username updated
        '403':
          description: Not authorized to update this user
        '404':
          description: User not found

  /users/me/photo:
    put:
      operationId: setMyPhoto
      security:
        - bearerAuth: []
      summary: Set the profile photo
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
             schema:
               type: object
               properties:
                 photo:
                   type: string # Base64
      responses:
         '200':
           description: Photo updated
         '403':
           description: Forbidden

  /conversations:
    get:
      operationId: getMyConversations
      summary: Get list of conversations for the user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'

  /conversations/{conversationId}:
    get:
      operationId: getConversation
      summary: Get details of a specific conversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
           description: Conversation details
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/Conversation'
        '404':
           description: Conversation not found

  /conversations/{conversationId}/messages:
    get:
      operationId: getConversationMessages
      summary: Get messages from a conversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
    post:
      operationId: sendMessage
      summary: Send a message to a conversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
               type: object
               properties:
                 content:
                   type: string
                   description: Text content
                 photo:
                   type: string
                   description: Optional photo
               required:
                 - content
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /conversations/{conversationId}/messages/{messageId}:
    delete:
      operationId: deleteMessage
      summary: Delete a message
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
        - name: messageId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Message deleted
        '403':
           description: Not the sender
        '404':
           description: Not found

  /conversations/{conversationId}/messages/{messageId}/comment:
    put:
       operationId: commentMessage
       summary: React to or comment on a message
       security:
         - bearerAuth: []
       parameters:
         - name: conversationId
           in: path
           required: true
           schema:
             type: integer
         - name: messageId
           in: path
           required: true
           schema:
             type: integer
       requestBody:
         required: true
         content:
           application/json:
             schema:
               type: object
               properties:
                 emoji:
                    type: string
       responses:
          '200':
             description: Comment/Reaction added

    delete:
       operationId: uncommentMessage
       summary: Remove a reaction/comment
       security:
         - bearerAuth: []
       parameters:
         - name: conversationId
           in: path
           required: true
           schema:
             type: integer
         - name: messageId
           in: path
           required: true
           schema:
             type: integer
       responses:
          '204':
            description: Comment removed

  /conversations/{conversationId}/messages/forward:
    post:
      operationId: forwardMessage
      summary: Forward a message to this conversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
           in: path
           required: true
           schema:
             type: integer
      requestBody:
         required: true
         content:
           application/json:
             schema:
               type: object
               properties:
                 original_message_id:
                    type: integer
      responses:
         '201':
           description: Message forwarded

  /groups/{conversationId}/members/{userId}:
    put:
      operationId: addToGroup
      security:
        - bearerAuth: []
      summary: Add a user to a group
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
           description: User added
    delete:
      operationId: leaveGroup
      security:
        - bearerAuth: []
      summary: Remove user from group (or self leave)
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
             type: integer
        - name: userId
          in: path
          required: true
          schema:
             type: integer
      responses:
         '204':
            description: User removed

  /groups/{conversationId}/name:
    put:
      operationId: setGroupName
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
      responses:
        '200':
           description: Name updated

  /groups/{conversationId}/photo:
    put:
      operationId: setGroupPhoto
      security:
        - bearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo:
                    type: string
      responses:
        '200':
          description: Photo updated
